export const ARTIFACTS = [
  { key: 'Dashboard', label: 'Dashboard', navItemName: 'Dashboard' },
  { key: 'Products', label: 'Productos', navItemName: 'Productos' },
  { key: 'Movements', label: 'Movimientos', navItemName: 'Movimientos' },
  { key: 'Quotations', label: 'Cotizaciones', navItemName: 'Cotizaciones' },
  { key: 'Reports', label: 'Reportes', navItemName: 'Reportes' },
  { key: 'Settings', label: 'Configuración', navItemName: 'Configuración' },
  { key: 'PettyCash', label: 'Caja Chica', navItemName: 'Caja Chica' },
  { key: 'BarcodeGenerator', label: 'Generador de Códigos', navItemName: 'Generador de Códigos' },
  { key: 'Categories', label: 'Categorías', navItemName: 'Categorías' },
  { key: 'Suppliers', label: 'Proveedores', navItemName: 'Proveedores' },
  { key: 'Clients', label: 'Clientes', navItemName: 'Clientes' },
  { key: 'PaymentMethods', label: 'Tipos de Pago', navItemName: 'Tipo de pago' },
  { key: 'SupplierPayments', label: 'Pagos a Proveedores', navItemName: 'Pagos a Proveedores' },
  { key: 'HelpCenter', label: 'Centro de Ayuda', navItemName: 'Centro de Ayuda' },
  { key: 'About', label: 'Acerca de', navItemName: 'Acerca de' },
];

export const ACTIONS = ['ver', 'leer', 'escribir', 'modificar', 'eliminar'];

export const LEGACY_DEFAULTS = {
  admin: {
    Dashboard: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    Products: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    Movements: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    Quotations: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    Reports: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    Settings: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    PettyCash: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    BarcodeGenerator: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    Categories: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    Suppliers: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    Clients: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    PaymentMethods: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    SupplierPayments: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    HelpCenter: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
    About: { ver: true, leer: true, escribir: true, modificar: true, eliminar: true },
  },
  almacenista: {
    Dashboard: { ver: true, leer: true, escribir: false, modificar: false, eliminar: false },
    Products: { ver: true, leer: true, escribir: false, modificar: false, eliminar: false },
    Movements: { ver: true, leer: true, escribir: true, modificar: false, eliminar: false },
    Quotations: { ver: true, leer: true, escribir: true, modificar: true, eliminar: false },
    Reports: { ver: true, leer: true, escribir: false, modificar: false, eliminar: false },
    Settings: { ver: true, leer: true, escribir: false, modificar: false, eliminar: false },
    PettyCash: { ver: true, leer: true, escribir: false, modificar: false, eliminar: false },
    BarcodeGenerator: { ver: true, leer: true, escribir: true, modificar: false, eliminar: false },
    Categories: { ver: true, leer: true, escribir: false, modificar: false, eliminar: true },
    Suppliers: { ver: true, leer: true, escribir: false, modificar: false, eliminar: false },
    Clients: { ver: true, leer: true, escribir: true, modificar: true, eliminar: false },
    PaymentMethods: { ver: true, leer: true, escribir: false, modificar: false, eliminar: false },
    SupplierPayments: { ver: false, leer: false, escribir: false, modificar: false, eliminar: false },
    HelpCenter: { ver: true, leer: true, escribir: false, modificar: false, eliminar: false },
    About: { ver: true, leer: true, escribir: false, modificar: false, eliminar: false },
  },
};
